spring:
  application:
    name: cuttlefish-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cuttlefish_db?serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true # 支持 FeignClient 的name属性 的相同名字

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

feign:
  hystrix:
    enabled: true
    command:
      default:  #default全局有效，service id指定应用有效
        execution:
          timeout:
            #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 10000 #断路器超时时间，默认1000ms

#开启驼峰命名转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml #配置mapper xml路径
