spring:
  application:
    name: cuttlefish-content

  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cuttlefish_db_prod?serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5 #初始化提供的连接数
      min-idle: 5 #数据库连接池的最小维持连接数
      max-total: 5  #最大的连接数
      max-wait-millis: 200  #等待连接获取的最大超时时间

  # redis配置
  redis:
    host: 127.0.0.1  # IP
    port: 6379  # 端口号
    password:   # 密码
#    lettuce:
#      pool:
#        max-active: 8 # 连接池最大连接数
#        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        min-idle: 0 # 连接池中的最小空闲连接
#        max-idle: 8 # 连接池中的最大空闲连接

  # 支持 FeignClient 的name属性 的相同名字
  main:
    allow-bean-definition-overriding: true

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

feign:
  hystrix:
    enabled: true
    command:
      default:  #default全局有效，service id指定应用有效
        execution:
          timeout:
            #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 10000 #断路器超时时间，默认1000ms


###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.thank.cuttlefish.pojo
  global-config:
    id-type: 0  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    #    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性


#控制台打印SQL
logging:
  level:
    com.thank.cuttlefish.content.mapper: DEBUG

